[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "account-abstraction/=lib/account-abstraction/contracts/",
    "solady/=lib/solady/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"